image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test

pre-commit:
  stage: test
  cache:
    key: pip-install-cache
    paths:
      - .cache/pip
  script:
    - pip install pre-commit==2.20.0 ruff==0.1.5 black==23.12.0
    - pre-commit install
    - pre-commit run --all-files -v || true
    - git diff
    - git diff --quiet --exit-code
  only:
    - main
    - merge_requests
