exclude: "^data/pipelines_db.json$|^examples/.*"

repos:
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
        # don't remove line-breaks in markdown
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
      - id: end-of-file-fixer

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        types: [yaml]

  # codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          ["--ignore-words-list", "hist, parms, wit, ba, te", "--skip", "*.txt"]

  # Make sure commited notebooks have no output
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  - repo: local
    hooks:
      # linter
      - id: ruff
        name: ruff
        entry: ruff --fix .
        language: system
        pass_filenames: false
      # formatter
      - id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false
