name: Python Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: pip install pre-commit==2.20.0 ruff==0.1.5 black==23.12.0

    - name: Install Pre-commit Hooks
      run: pre-commit install

    - name: Run Pre-commit Hooks
      run: pre-commit run --all-files -v || true

    - name: Check for Changes
      run: |
        git diff
        git diff --quiet --exit-code
